Bypass parser to exit when Hoa is included twice.
Hoa\Core has a special constant HOA to detect whether the core is
included twice. Unfortunatly, the parser failed with the function ƒ
before executing the code. We move the ƒ function into
Hoa\Core\Consistency to fix this.

Example:
    require '/usr/local/lib/Hoa/Core/Core.php';
    require '/usr/local/lib/Hoa/Core/Core.php';

Before:
    PHP Fatal error:  Cannot redeclare ƒ() (previously declared in…
    Fatal error: Cannot redeclare ƒ() (previously declared in…

After:
    Hoa main file (Core.php) must be included once.