Exception: Create `Hoa\Irc\Exception\ErrorReplies`.
An error in IRC is called an error reply. It is a range of 199 code,
from 400 to 599.

A mapping from code to name is provided for the well-known error
replies.